name 'poise-fpm'
maintainer 'Luis De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'Installs/Configures fpm'
long_description 'Installs/Configures fpm'
version '0.0.4'

depends 'rbenv'
depends 'poise'
